In [43]:
import os
import glob
import pandas as pd
import numpy as np
import joblib
thompson_results = glob.glob("Experiment results/Thompson/Experiment1/*")
results1 = thompson_results[21]
results1.split("/")[-1].split(r"__")

['p_control=1',
 'mde=0',
 'prob_super=0.8',
 'batch_size_share_mu=0.09',
 'multi_armed=False']

In [38]:
df[0][1]['probability_superiority'][2]

[array([358, 358], dtype=uint16),
 array([108, 108], dtype=uint16),
 array([  0, 784], dtype=uint16),
 array([  0, 724], dtype=uint16),
 array([452, 452], dtype=uint16),
 array([  0, 715], dtype=uint16),
 array([219, 219], dtype=uint16),
 array([143, 143], dtype=uint16),
 array([255, 255], dtype=uint16),
 array([  0, 425], dtype=uint16),
 array([230, 230], dtype=uint16),
 array([206, 206], dtype=uint16),
 array([217, 217], dtype=uint16),
 array([107, 107], dtype=uint16),
 array([100, 100], dtype=uint16),
 array([253, 253], dtype=uint16)]

In [39]:
df[0][1]

defaultdict(tuple,
            {'probability_superiority': (array([[0.287, 0.713],
                     [0.215, 0.785],
                     [0.343, 0.657],
                     [0.379, 0.621],
                     [0.452, 0.548],
                     [0.466, 0.534],
                     [0.417, 0.583],
                     [0.459, 0.541],
                     [0.405, 0.595],
                     [0.394, 0.606],
                     [0.355, 0.645],
                     [0.325, 0.675],
                     [0.295, 0.705],
                     [0.254, 0.746],
                     [0.218, 0.782],
                     [0.194, 0.806]]),
              array([0.744, 0.743, 0.336, 0.264, 0.174, 0.158, 0.172, 0.144, 0.159,
                     0.162, 0.173, 0.183, 0.191, 0.211, 0.23 , 0.238]),
              [array([358, 358], dtype=uint16),
               array([108, 108], dtype=uint16),
               array([  0, 784], dtype=uint16),
               array([  0, 724], dtype=uint16),
            

In [30]:
df

[(defaultdict(int, {'probability_superiority': 1}),
  defaultdict(tuple,
              {'probability_superiority': (array([[0.381, 0.619],
                       [0.242, 0.758],
                       [0.208, 0.792],
                       [0.181, 0.819]]),
                array([0.807, 0.721, 0.651, 0.598]),
                [array([234, 234], dtype=uint16),
                 array([271, 271], dtype=uint16),
                 array([201, 201], dtype=uint16),
                 array([217, 217], dtype=uint16)],
                [array([0, 0]), [1, 1], [2, 2], [2, 3], [2, 4]]),
               2: (),
               3: (),
               1: (),
               0: ()})),
 (defaultdict(int, {'probability_superiority': 1}),
  defaultdict(tuple,
              {'probability_superiority': (array([], dtype=float64),
                array([], dtype=float64),
                [],
                [array([0, 0])])})),
 (defaultdict(int, {'probability_superiority': 1}),
  defaultdict(tuple,
              {'p

In [ ]:
# Костыльное решение (фиксим, разделяя __)
p_control_list = [0.1, 0.2, 0.3, 0.4, 0.5]
mde_list = np.linspace(0.01, 0.5, 10)
# result_experiments_df = pd.DataFrame(index=pd.MultiIndex.from_product(
#                                      [p_control_list, mde_list],
#                                      names=["distr_type", "mean_control", "mde_test_effect",
#                                             "sigma_control", "sigma_diff", "size"]),
#                                      columns=['p_value_Student', 'p_value_MU', 'p_value_BS',
#                                               "control_bs_means", "test_bs_means"])

In [ ]:
files = glob.glob('Experiment results/Bayesian/Experiment1/*')
for f in files:
    os.remove(f)

In [ ]:

n

In [ ]:
def get_size(theta_c, theta_t, alpha, beta):
    # вычисляем квантили нормального распределения
    t_alpha = stats.norm.ppf(1 - alpha, loc=0, scale=1)
    t_beta = stats.norm.ppf(beta, loc=0, scale=1)
    # решаем уравнение относительно n
    n = t_alpha*np.sqrt(theta_t*(1 - theta_t))
    n -= t_beta*np.sqrt(theta_c*(1 - theta_c))
    n /= theta_c - theta_t
    return int(np.ceil(n*n))

n_max = get_size(0.1, 0.11, 0.05, 0.2)
n_max